from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import InquiryViewSet

# Router automatically creates all the URL patterns.
router = DefaultRouter()
router.register(r'inquiries', InquiryViewSet)

urlpatterns = [
    path('', include(router.urls)), #include all the URLs generated by the router
]